# Generated by Django 2.1.5 on 2019-03-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Crypto_Name', models.CharField(max_length=30)),
                ('Crypto_Value', models.FloatField(max_length=10)),
            ],
        ),
    ]
