# Generated by Django 2.1.5 on 2019-03-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApps', '0002_auto_20190312_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='cryptocurrency_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chart',
            name='cryptocurrency_value',
            field=models.FloatField(max_length=15),
        ),
    ]
