# Generated by Django 2.1.5 on 2019-04-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApps', '0003_auto_20190312_0655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
