# Generated by Django 2.1.5 on 2019-04-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency_name', models.CharField(max_length=30)),
                ('cryptocurrency_value', models.FloatField(max_length=15)),
            ],
        ),
    ]
